#!/bin/bash

# Dummy run for building image
if [ "${MODE}" = "build" ]; then
  sleep infinity
fi

# Configure AriaNG & Rclone WebUI
sed -i 's|rpcInterface:"jsonrpc"|rpcInterface:"'"${GLOBAL_PORTAL_PATH/\//}"'/jsonrpc"|g' /.hms/ariang/js/aria-ng-f1dd57abb9.min.js
sed -i 's|ipAddress:a|ipAddress:`${window.location.protocol}//${window.location.hostname}'"${GLOBAL_PORTAL_PATH}"'/rclonerc`|g' /.hms/rcloneweb/build/static/js/3.90421092.chunk.js

# Configure homer
cp /.hms/homer_conf/* /.hms/homer/assets/tools/
cp /.hms/homer_conf/homer_${GLOBAL_LANGUAGE}.yml /.hms/homer/assets/config.yml
sed -i "s|GLOBAL_PORTAL_PATH|${GLOBAL_PORTAL_PATH}|g;s|VMESS_PATH|${VMESS_PATH}|g;s|VMESS_UUID|${VMESS_UUID}|g" /.hms/homer/assets/config.yml

# Run language script
/.hms/caddy_init_${GLOBAL_LANGUAGE}.sh

# Configure Caddyfile
HASH="$(caddy hash-password --plaintext ${GLOBAL_PASSWORD})"
sed -i "s|HASH|${HASH}|g" /.hms/Caddyfile

# Run caddy
exec 2>&1
exec caddy run --config /.hms/Caddyfile --adapter caddyfile
